### ISSUE TITLE
tox --> nox now?

### ISSUE THREAD

**Issue by vvsagar** [scikit-hep/decaylanguage#198]
Hello! I have been using this package in last few weeks for some preliminary studies on B decays at Belle(II) and found it very useful! Thank you for making it :)

I also have a few suggestion, which I will try to communicate in coming weeks. But before that, you mention `tox` in step 4 of `CONTRIBUTING.rst`, but I see that the `tox.ini` is deleted in the PR #34. 

Am I missing something here or did you move from `tox` to `nox` now and `CONTRIBUTING.rst` needs an update?

**Comment by henryiii** [comment]
This was originally produced by a package cookiecutter (it predates scikit-hep/cookie) that included a tox file. Tox was never really used properly or tested, to the best of my knowledge, it just happened to be there, and was mentioned in CONTRIBUTING due to the template. We now provide and fully support nox for simple/fast development environments.

Good catch, CONTRIBUTING needs an update!

**Comment by henryiii** [comment]
For some reason I'm now envisioning a little furry mouse running up and down the keyboard, slipping around and hitting random buttons. :)
